### ISSUE TITLE
[1.20.1] [Forge] Non-op players get stuck on carpets

### ISSUE THREAD

**Issue by 630R63** [noeppi-noeppi/BingoLobby#10]
This issue has 2 different problems, but the solution might fix both of them.
Playing multiplayer on a dedicated server using Forge 47.0.35 and Bongo 1.20.1-4.0.1 + BingoLobby 1.20.1-4.0.1

After completing a game and returning from the overworld:
1) Non-op players get stuck on colored carpets and the message that "you can't join a team when there is no game started" gets spammed in their chat. They are unable to move. Op players just get sent to the middle of the lobby when they step over the carpets.

2) After creating a new game, the non-op, non-vip players get stuck when stepping on the yellow carpet (vip team) and their chat is spammed that they are not vip and cannot join the vip team. Again, they cannot move. They just freeze in place. Op players just get teleported to the middle as usual.

**Comment by noeppi-noeppi** [comment]
Not reproducible for me. Could be a mod compatibility issue. Can you try with only BingoLobby, Bongo and LibX?

**Comment by noeppi-noeppi** [comment]
I am going to close this now due to lack of response. If the issue still persist, please feel free to open a new one and provide the requested information.
